export const ADD_PARTICIPANT_REQUEST = "ADD_PARTICIPANT_REQUEST";
export const ADD_PARTICIPANT_SUCCESS = "ADD_PARTICIPANT_SUCCESS";
export const ADD_PARTICIPANT_FAILURE = "ADD_PARTICIPANT_FAILURE";

export const FETCH_PARTICIPANTS_REQUEST = "FETCH_PARTICIPANTS_REQUEST";
export const FETCH_PARTICIPANTS_SUCCESS = "FETCH_PARTICIPANTS_SUCCESS";
export const FETCH_PARTICIPANTS_FAILURE = "FETCH_PARTICIPANTS_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const VOTE_REQUEST = "VOTE_REQUEST";
export const VOTE_SUCCESS = "VOTE_SUCCESS";
export const VOTE_FAILURE = "VOTE_FAILURE";
